version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: .\ERM Tests.postman_collection.json
          environment: .\postman-api-testing\ERM.postman_environment.json
          folder: User Assignments
